apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-lightgallery-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          help: 填写扫描图片的区域的 DOM 节点，支持 CSS 选择器，如：#content
          label: DOM 节点选择
          name: dom_selector
          validation: required
