apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginLightGallery
spec:
  enabled: true
  version: 1.0.0-alpha.1
  requires: "*"
  author: halo-dev
  logo: https://halo.run/logo
  settingName: plugin-lightgallery-settings
  configMapName: plugin-lightgallery-configMap
  homepage: https://github.com/halo-sigs/plugin-lightgallery
  displayName: "lightgallery.js 灯箱"
  description: "提供对 lightgallery.js 的集成，支持在内容页放大显示图片"
  license:
    - name: "MIT"
